[package]
name = "xtask"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
argon2 = "0.5"
password-hash = { version = "0.5", features = ["getrandom"] }
rpassword = "7.5"
thiserror = "2"
toml = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
prost = "0.13"
sysprobe = { path = "../sysprobe" }
vpn-server = { path = "../vpn-server" }

[dev-dependencies]
tempfile = "3"
