[package]
name = "user-store"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5"
async-trait = "0.1"
thiserror = "2"
sqlx = { version = "0.9", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tempfile = "3"
password-hash = { version = "0.5", features = ["getrandom"] }
